name = "PredatorPrey"
uuid = "496ee565-671a-4115-bfb7-f0a86f65f54d"
authors = ["Ivan Utkin <iutkin@ethz.ch>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.10.15"
